### ISSUE TITLE
EXECUTION FAILURE

### ISSUE THREAD

**Issue by liaotian1005** [detekt/sonar-kotlin#103]
ERROR: Error during SonarQube Scanner execution
ERROR: org/jetbrains/kotlin/com/intellij/openapi/fileTypes/FileType
ERROR: Caused by: org.jetbrains.kotlin.com.intellij.openapi.fileTypes.FileType

**Comment by schalkms** [comment]
Could you please provider more context concerning when and where this exception pops up?
Also a stack trace would help us to track down this problem.
