### ISSUE TITLE
Where is detekt in sonarQube ? 

### ISSUE THREAD

**Issue by mirecalu** [detekt/sonar-kotlin#130]
Hi,

I've pulled the docker image of sonarQube 8.2-community and installed detekt from the Marketplace. 
Then, I configured it in the Administration configuration settings and finally ran ./gradlew sonarqube command : Build successful.

However, I dont see on sonar any error report from detekt ? Where am I supposed to see detekt errors ? 

Thanks

**Comment by arturbosch** [comment]
Hi!

Have you enabled the detekt rules in your quality profile ?
Note only the default sonar Kotlin rules are run if not explicitly configured.

**Comment by mirecalu** [comment]
Perfect. It's as simple as that.

Thank's for your help ;)
