### ISSUE TITLE
What is reason to increase sonar api version from 6.7.7?

### ISSUE THREAD

**Issue by Romqqa** [detekt/sonar-kotlin#134]
Hello!
Can you tell me please what is reason to increase sonar api version from 6.7.7?
I want to use lates sonar-detekt plugin and latest detekt versions on sonar 6.7.7.
Can I do it?
I tried to reduce version sonar api to 6.7.7 and everything seems fine.

Thanks!

**Comment by arturbosch** [comment]
Hi!
7.9 is the latest LTS version of Sonarqube so it was natural to upgrade to it: https://www.sonarqube.org/sonarqube-7-9-lts/
I'm not aware of any incompatibilities introduced in 7.9 for us.
So if you have successfully compiled sonar-detekt on 6.7.7 it should be fine, I guess :).

**Comment by Romqqa** [comment]
Thank's for your help!
