### ISSUE TITLE
 Update to detekt 1.17.1

### ISSUE THREAD

**Issue by ondrejlerch** [detekt/sonar-kotlin#142]
Could you please release sonar-kotlin with latest detekt 1.17.1?
Detekt version in sonar-kotlin is 1.14.1 which is outdated (2020-09-29).

Are you a) updating Detekt regularly? If so, how often?
Or b) should sonar-kotlin users clone sonar-kotlin, make necessary changes and build their own sonar-kotlin in order to use latest detekt?
As a user I would prefer a) since that would be simpler.

Many thanks!

**Comment by cortinico** [comment]
> As a user I would prefer a) since that would be simpler.

Yup that's ideally the desired approach.

Detekt is quite big and we focus much of our effort to `detekt/detekt`. The other tools (sonar-kotlin, intellij plugin, compiler plugin, etc.) gets updated whenever there is a request or when we have bandwidth for it.

We're already understaffed and open to new contributors 🙏 

Let's try to release a new version of it with Detekt 1.18.0 that will be out in the next days 👍

**Comment by ondrejlerch** [comment]
Thanks for your effort and great detekt tool 👍 I suggest that at least once a year there is overall update to new version of detekt of the whole suite including sonar-kotlin, intellij plugin and detekt-maven-plugin. We use all mentioned tools in our pipeline so this would help us (and others) to use such detekt version with appropriate detekt-config.yml and avoid failures caused by inconsistent versions which happened to me when I tried to update detekt-maven-plugin without updating sonar-kotlin 😊

**Comment by cortinico** [comment]
> I suggest that at least once a year there is overall update to new version of detekt of the whole suite including sonar-kotlin, intellij plugin and detekt-maven-plugin

Technically the latest release of sonar-kotlin was less than one year ago (October 2020).
Ideally we would also like to keep the tools as aligned as possible (i.e. update all the tools once we release a new version), but yeah, that depends on our capacity.

**Comment by Ozsie** [comment]
Hi, I created a PR for Detekt 1.18.1, #144

**Comment by cortinico** [comment]
And version 2.4.0 is out 🎉
