### ISSUE TITLE
Detekt start analyze java and kotlin file in build/.gradle dir

### ISSUE THREAD

**Issue by Monax111** [detekt/sonar-kotlin#145]
sonarqube.gradle.plugin - 3.3
Sonar server Community Edition Version 8.5.1 (build 38104)
gradle - 7.1.1
run in gitlab 14.1.0

I think that problem in function:
```
io.gitlab.arturbosch.detekt.sonar.sensor.DetektConfiguration.createSpec() 
```
then evaluate inputPaths field
```
inputPaths = listOf(baseDir)
```
I have one-module project. If i apply sonar plugin, baseDir = rootDir. In root dir gradle create very many cache/tmp file. This base dir map to property pathsToAnalyze in function [createCompilerConfiguration ](https://github.com/detekt/detekt/blob/main/detekt-parser/src/main/kotlin/io/github/detekt/parser/KotlinEnvironmentUtils.kt#L71). Because of this javaFiles contains all file(include cache/tmp file)

![image](https://user-images.githubusercontent.com/17501801/133336741-b40a7c09-f220-4a01-b500-295a240f30e8.png)

[Full log for this situation](https://community.sonarsource.com/uploads/short-url/uwMPYE4Sqnfwm1HEdZlRcokEqYc.txt) 

I suggest change 
```
inputPaths = configuration.get("sonar.sources")
```
this improvement allows you to configure detekt only for sources file

**Comment by Monax111** [comment]
@cortinico could you see this problem?

**Comment by cortinico** [comment]
> I suggest change

Don't you mind sending a PR?

**Comment by Monax111** [comment]
I try, but I've never done this before in open source projects.

**Comment by cortinico** [comment]
No problem. Just try and if you get stuck let us know :)

**Comment by Monax111** [comment]
I create commit, but can't push it. I need correct permission?
```
ERROR: Permission to detekt/sonar-kotlin.git denied to Monax111.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

**Comment by cortinico** [comment]
> I need correct permission?

You would need to create a fork first. And push your branch to your fork.
You can find a guide here https://docs.github.com/en/get-started/quickstart/fork-a-repo

**Comment by Monax111** [comment]
Well, I think this is a very strange way, but I did it)

**Comment by Monax111** [comment]
Hi, what i must do, for merge PR? Because of this problem, we have many builds which throw OutOfMemory:metaspce. I would like to quickly deliver these changes to our infrastructure

**Comment by cortinico** [comment]
> Hi, what i must do, for merge PR? Because of this problem, we have many builds which throw OutOfMemory:metaspce. I would like to quickly deliver these changes to our infrastructure

There seems to be failures on the CI.
Let's fix them and we can merge it. Once it's merged, we would need to wait for a new release.
If you have urgency, the best would be to make your own release and use the local artifact in your sonar instance.

**Comment by Monax111** [comment]
`Let's fix them and we can merge it`
I fix failures, Can you start CI again ?

**Comment by cortinico** [comment]
Yup now it's merged 👍

**Comment by Monax111** [comment]
Can You explain, how i can add my custom release to my sonar instance? Some instruction? or guide?

**Comment by cortinico** [comment]
> Can You explain, how i can add my custom release to my sonar instance? Some instruction? or guide?

The instructions are basically the one listed here https://github.com/detekt/sonar-kotlin#building-from-source
