### ISSUE TITLE
2.4.0 in marketplace

### ISSUE THREAD

**Issue by vvalencia-cl** [detekt/sonar-kotlin#149]
Hi. 
I can't find the new version (2.4.0) in the marketplace.
What can I do?

I suppose that this is where the marketplace gets plugin's versions: https://update.sonarsource.org/detekt.json

Thanks in advance

**Comment by cortinico** [comment]
Yeah I sent a PR some time ago but I haven't received any follow up: https://github.com/SonarSource/sonar-update-center-properties/pull/250/
Waiting for that to be merged

**Comment by cortinico** [comment]
Closing as this is released
