### ISSUE TITLE
Provide integration example

### ISSUE THREAD

**Issue by JackLeo** [detekt/sonar-kotlin#37]
Hi, It would be great if documentation would include an example where it works with detect analysis.

**Comment by marcinbak** [comment]
You can have a look here https://github.com/marcinbak/android-sonar-kotlin for a working integration, however code coverage is not passed to Sonarqube (I could not make it work). I've created an issue to provide working coverage setup https://github.com/arturbosch/sonar-kotlin/issues/46

**Comment by arturbosch** [comment]
I've mentioned your sample project @marcinbak in the readme, thanks!
