### ISSUE TITLE
Any plans to make the plugin officially available on the SonarQube Update Center?

### ISSUE THREAD

**Issue by Vismayhr** [detekt/sonar-kotlin#58]
Hello,
I was in a discussion with SonarSource and they said that the individual contributor of the Community plugins have to request for the their plugin to be included in the Update Center on SonarQube.

As we use an enterprise edition of SonarQube, by policy we use only official plugins on our SonarQube instance. We've had a lot of requests to support kotlin on our instance, so could you please let us know if you have any plans to make it available on the update center?

Regards,
Vismay

**Comment by arturbosch** [comment]
Hey, thanks for the question. Everything is in the last comment of https://github.com/arturbosch/sonar-kotlin/issues/6 is still valid. I'm confident I will have more time by next week after my masterthesis is handed over ^^

**Comment by Altoyyr** [comment]
I think it would still be good to have it up on the update center even if it is not completely fleshed out. 
People can still decide if they want it or not but it will help with maintenance. 

But first take care of your thesis :D

**Comment by arturbosch** [comment]
Thanks!
Yes, sonar-kotlin does not need to be 1.0 for the update center but detekt has to be :).

**Comment by hameno** [comment]
It looks like the official plugin from sonar is now available: https://docs.sonarqube.org/display/PLUG/SonarKotlin
I just got it offered as an update from this plugin. Probably not intentional, right?

**Comment by arturbosch** [comment]
Yep, seems like they are using the same key as I am. Don't know about the future of this plugin... They allow to import detekt issues ^^

**Comment by hameno** [comment]
I quickly tested it and saw no coverage or test numbers, will stay on 0.5.0 for now...

**Comment by dgulick-jama** [comment]
Given the 1.0 release of detekt will this get officially published, maybe under a different key like `kotlin-detekt` if they are taking the one you've been using? I'm using SonarKotlin currently but I'd like to try out this plugin instead since it's more likely to keep up to date, but I can't install any non-published plugins on my Sonar system.

**Comment by arturbosch** [comment]
Jap, this should be the way to go. `kotlin-detekt` sounds good. Will plan this ticket for my next weeks. Thanks for the reminder.

**Comment by DimaLegeza** [comment]
In our team we are also struggling with default KotlinSonar plugin. So I am wondering about the plans on this ticket :) Would be absolutely brilliant to be able to install this plugin from update center as I am also unable to reach unix-box to install it that way. Thanks a lot for your efforts and time :)

**Comment by schalkms** [comment]
duplicate #6 
However, I think this could now be tackled, since this plugin is on version 1.3.2.
