### ISSUE TITLE
Does the Jacoco support in SonarQube 5.6.4 for a multi module & multi language project

### ISSUE THREAD

**Issue by sidd9433** [detekt/sonar-kotlin#61]
Does the Jacoco support in SonarQube 5.6.4 for a multi module & multi language project. I am trying to get it work but no luck. 

Issues

1. No coverage reported for kotlin code. 
2. Not counting the number of tests written in kotlin.

Is there a n example available to refer?

**Comment by arturbosch** [comment]
No, unfortunately jacoco coverage does not work for multi module projects. Only for single module we got it to work. One user made it work for multi modules when modifying the jacoco reports into one report file.
I don't use code coverage and can't help you here, sorry.

Counting test cases in kotlin is not yet implemented.

**Comment by schalkms** [comment]
duplicate #36
