### ISSUE TITLE
unsatisfied dependency

### ISSUE THREAD

**Issue by yooouuri** [detekt/sonar-kotlin#64]
The following error occur when i try to build something:

> io.gitlab.arturbosch.detekt.sonar.jacoco.KotlinJaCoCoSensor has unsatisfied dependency 'interface org.sonar.plugins.java.api.JavaResourceLocator' for constructor 'public io.gitlab.arturbosch.detekt.sonar.jacoco.KotlinJaCoCoSensor(org.sonar.api.batch.fs.FileSystem,org.sonar.plugins.java.api.JavaResourceLocator,org.sonar.java.JavaClasspath)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@3a62c01e:133<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@125290e5:213<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@15a34df2:7<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@70f43b45:30<|

**Comment by mdr** [comment]
I get this error too, running Sonar 6.7.3 with version 0.4.2 of the plugin

**Comment by p1gmale0n** [comment]
in my case i get this error too with SonarQube 7.1 and plugin 0.4.2 
issue state:
1) started SonarQube without plugin and init db
2) restarted SonarQube with pluging

**Comment by flosell** [comment]
Can confirm what @p1gmale0n said: Removing all SonarQube data and starting from a fresh instance with the plugin installed fixed the problem. 

SonarQube 6.7.4 and Plugin 0.4.2

**Comment by arturbosch** [comment]
Thank you for posting your experience and solution/hack!

**Comment by arturbosch** [comment]
Code coverage feature will be dropped in 2.0.
Official SonarKotlin plugin supports code coverage.
This plugin will work next to the official one.
