### ISSUE TITLE
Code Coverage for nested classes ommitted

### ISSUE THREAD

**Issue by brandon-rude** [detekt/sonar-kotlin#67]
Jacoco reports show the coverage for kotlin nested classess but it is not displayed in sonar. Any idea why?

**Comment by arturbosch** [comment]
Nope sorry, it seems that there are quite some problems with jacoco and kotlin together.

**Comment by arturbosch** [comment]
Nothing we can do about. Need to wait until jacoco's Kotlin supports gets better.
