### ISSUE TITLE
Add support for ktlint reports

### ISSUE THREAD

**Issue by 4brunu** [detekt/sonar-kotlin#84]
Hi, first of all, thanks for this amazing plugin!
I need to send ktlint reports to SonarQube, but from what I looked into, this is not supported, or is it?
Thanks

**Comment by arturbosch** [comment]
Hey, thanks for the kind words.
Unfortunatelly the formatting rule set is not yet supported in sonar-kotlin (which wraps KtLint in detekt).
I think just adding the `detekt-formatting` dependency into pom.xml would just work out of box.

**Comment by 4brunu** [comment]
And what about just lint report, without formatting?

**Comment by arturbosch** [comment]
Yes, `detekt-formatting` can just produce the lint report of KtLint without actually formatting. This will be the only supporting feature in `sonar-kotlin` as we do not want to mess with users code.
