### ISSUE TITLE
Sonarqube SpreadOperator Rule

### ISSUE THREAD

**Issue by ehei** [detekt/sonar-kotlin#88]
When running a Sonarqube (7.4) analysis using plugin version 0.5.2, Sonarqube will complain while analyzing and fail our build with the following error:

> The rule 'DetektRuleKey(repositoryKey=detekt-kotlin, ruleKey=SpreadOperator, active=true, issue=Issue(id='SpreadOperator', severity=Performance, debt=20min))' does not exist.

For the Kotlin-Way default rule set, I see that rule there. Is there something I am missing?

**Comment by mikesmithson** [comment]
Actually, this seems to be failing for all violations that are triggered with the 0.5.2 plugin installed in Sonarqube 7.4 community.

**Comment by arturbosch** [comment]
Please reply if this is still an issue for you in 1.1.0.
